version: '3'

services:
  db:
    image: postgres
    container_name: 'postgres-db'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: 'redis-db'
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  app:
    build: .
    container_name: 'django'
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: 'celery'
    command: celery -A config worker -l INFO -P eventlet
    depends_on:
      - redis
